name: app_gym
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^8.0.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  bloc: ^8.1.4
  go_router: ^14.6.0
  dio: ^5.7.0
  shared_preferences: ^2.3.3
  intl: ^0.19.0
  hexcolor: ^3.0.1
  google_fonts: ^6.2.1
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  retrofit: ^4.4.1
  injectable: ^2.5.0
  logger: ^2.5.0
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^2.4.4
  flutter_svg: ^2.0.15
  collection: ^1.18.0
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  injectable_generator: ^2.6.2
  retrofit_generator: ^9.1.5

  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icons/
